config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items

  get 'scrape', to: 'items#scrape'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  def scrape
    user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"

    doc = Nokogiri::HTML(open(self.link, 'User-Agent' => user_agent))

    selected_object = doc.css(self.selector)

    to_be_saved = "<ol>"

    selected_object.each do |row|
      # to_be_saved += "<li>#{row.text}</li>"
      if self.extra == "uniqlo"
        to_be_saved += "<li><p>#{row.css('div:nth-child(3) > h2 > a').text}</p>"
        to_be_saved += "<p>#{row.css('div:nth-child(3) > div:nth-child(2) > p:nth-child(2) > span:nth-child(1)').text}</p></li>"
        to_be_saved += "<img src=#{row.css('img').attr('data-original').text}>"
      else
        to_be_saved += "<li>#{row.text}</li>"
      end
    end

    to_be_saved += "</ol>"

    self.result = to_be_saved

    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
  end

  def new
    # modal popup + ajax?
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'new'
    end

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end

  def scrape
    @items = Item.all

    @items.each do |item|
      item.scrape
    end

    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:link, :selector, :extra, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.slim
= form_for @item do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :link
    = f.text_field :link
  p
    = f.label :selector
    = f.text_field :selector
  p
    = f.label :extra
    = f.text_area :extra
  p
    = f.submit 'Save'
    
= link_to 'Back', items_path

app/views/items/edit.slim
h3 Edit Item

= render 'form'

app/views/items/index.slim
h2 All items

p
  = link_to 'Add New', new_item_path, class: "btn btn-primary"
p
  = link_to 'Scrape', scrape_path, class: "btn btn-default"

- @items.each do |item|
  div.col-xs-4
    .panel.panel-default
      .panel-heading
        h4 #{item.title}
        a href="#{item.link}" #{item.link}
        p Last scrape #{time_ago_in_words(item.updated_at)} ago
      .panel-body
        - if not item.result.nil?
          p = item.result.html_safe
      .panel-footer
        = link_to 'Edit', edit_item_path(item), class: "btn btn-xs btn-primary"
        = link_to 'Delete', item_path(item), method: :delete, class: "btn btn-xs btn-danger pull-right"

app/views/items/new.slim
h3 New Item

= render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScrapper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>